bitpay:
  design:
    mode: "standard"
    hero:
      bgColor: "#2a3f90"
      title: "BitPay Demo Store"
      body: "Please fill out the fields below to request an invoice."
    logo: "https://bitpay.com/_nuxt/img/bitpay-logo-blue.1c0494b.svg"
    posData:
      fields:
        - type: "select"
          required: true
          id: "store"
          name: "store"
          label: "Store"
          options:
            - id: "store-1"
              label: "Store 1"
              value: "store-1"
            - id: "store-2"
              label: "Store 2"
              value: "store-2"
        - type: "fieldset"
          required: true
          name: "register"
          label: "Register #"
          options:
            - id: "register-1"
              label: "1"
              value: "1"
            - id: "register-2"
              label: "2"
              value: "2"
        - type: "text"
          required: true
          id: "reg_transaction_no"
          name: "reg_transaction_no"
          label: "Reg/Transaction #"
        - type: "price"
          required: true
          id: "price"
          name: "price"
          currency: "USD"
          label: "Price"
    donation:
      denominations:
        - 2800
        - 1000
        - 500
        - 100
        - 50
      enableOther: true
      footerText: "Contributions or gifts to RECIPIENT are not tax deductible. Contributions are limited to $10,000 per PAC per election cycle ($5,000 primary and $5,000 general) and $5,600 per individual per election cycle ($2,800 primary and $2,800 general). Contributions from the general treasury funds of corporations, labor unions, and national banks are prohibited. Federal contractors and foreign nationals who are not admitted for permanent residence in the United States are prohibited from making contributions. All contributions must be from personal funds and may not be reimbursed or paid by any other person. Federal law requires us to use our best efforts to collect and report the name, mailing address, occupation, and name of employer of individuals whose contributions exceed $200 in an election cycle."
      buttonSelectedBgColor: "#2a3f90"
      buttonSelectedTextColor: "#ffffff"
  token:
  notificationEmail:

server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:./data/kiosk
    username: test
    password: test
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format: true
  main:
    banner-mode: off

app-url: "https://localhost:8080"